events{

}
http{

    upstream backend {
       server server1:7000;
       server server2:7000;
       server server3:7000;
    }
    srever{
        listen 80;
        location /{
           return 200 "Hello from Nginx pankaj side";
           proxy_pass  http://backend;
        }
    }
}


# events{

# }

# upstream backend{
#     server server1:7000;
#     server server2:7000;
#     server server3:7000;
#     server server4:7000;
# }
# http{
#     server{
#         listen 80;
#         location /{
#             return 200 "hello from nginx side";
#             proxy_pass http://backend;
#         }
#     }
# }

